# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("calculator_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MainWindow_2 = QtWidgets.QWidget(MainWindow)
        self.MainWindow_2.setObjectName("MainWindow_2")
        self.btn_to = QtWidgets.QPushButton(self.MainWindow_2)
        self.btn_to.setGeometry(QtCore.QRect(130, 150, 93, 28))
        self.btn_to.setObjectName("btn_to")
        self.btn_ci = QtWidgets.QPushButton(self.MainWindow_2)
        self.btn_ci.setGeometry(QtCore.QRect(240, 150, 93, 28))
        self.btn_ci.setObjectName("btn_ci")
        self.btn_ca = QtWidgets.QPushButton(self.MainWindow_2)
        self.btn_ca.setGeometry(QtCore.QRect(270, 110, 93, 28))
        self.btn_ca.setObjectName("btn_ca")
        self.btn_bo = QtWidgets.QPushButton(self.MainWindow_2)
        self.btn_bo.setGeometry(QtCore.QRect(270, 80, 93, 28))
        self.btn_bo.setObjectName("btn_bo")
        self.txt_1 = QtWidgets.QLineEdit(self.MainWindow_2)
        self.txt_1.setGeometry(QtCore.QRect(140, 80, 113, 22))
        self.txt_1.setObjectName("txt_1")
        self.txt_2 = QtWidgets.QLineEdit(self.MainWindow_2)
        self.txt_2.setGeometry(QtCore.QRect(140, 110, 113, 22))
        self.txt_2.setObjectName("txt_2")
        self.lbl_1 = QtWidgets.QLabel(self.MainWindow_2)
        self.lbl_1.setGeometry(QtCore.QRect(70, 80, 55, 16))
        self.lbl_1.setObjectName("lbl_1")
        self.lbl_2 = QtWidgets.QLabel(self.MainWindow_2)
        self.lbl_2.setGeometry(QtCore.QRect(70, 110, 55, 16))
        self.lbl_2.setObjectName("lbl_2")
        self.label = QtWidgets.QLabel(self.MainWindow_2)
        self.label.setGeometry(QtCore.QRect(130, 200, 55, 16))
        self.label.setObjectName("label")
        self.lbl_result = QtWidgets.QLabel(self.MainWindow_2)
        self.lbl_result.setGeometry(QtCore.QRect(210, 200, 55, 16))
        self.lbl_result.setText("")
        self.lbl_result.setObjectName("lbl_result")
        MainWindow.setCentralWidget(self.MainWindow_2)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_to.setText(_translate("MainWindow", "topla"))
        self.btn_ci.setText(_translate("MainWindow", "cıkar"))
        self.btn_ca.setText(_translate("MainWindow", "carp"))
        self.btn_bo.setText(_translate("MainWindow", "bol"))
        self.lbl_1.setText(_translate("MainWindow", "sayı1:"))
        self.lbl_2.setText(_translate("MainWindow", "sayı 2:"))
        self.label.setText(_translate("MainWindow", "sonuc:"))
